version: '3'
services:
    api:
        build: .
        container_name: rota_viagem_dev
        volumes : 
            - .:/app
        command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
